version: '3.8'

services:
  backend:
    build:
      context: ./hse_practice_back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file:
      hse_practice_back/.env
    networks:
      - hse-p-net

  frontend:
    build:
      context: ./hse_practice_front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    networks:
      - hse-p-net

networks:
  hse-p-net:
    driver: bridge
